name: peer_tube_api_sdk
version: 1.0.6
description: A Dart/Flutter SDK for interacting with PeerTube instances. Easily connect to PeerTube nodes, fetch video data, manage accounts, and more.
homepage: https://www.siriuschain.io
repository: https://github.com/RustLangLatam/peertube_api_sdk
issue_tracker: https://github.com/RustLangLatam/peertube_api_sdk/issues
documentation: https://github.com/RustLangLatam/peertube_api_sdk#readme
topics:
  - peertube
  - peertube-api
  - peertube-sdk
  - peer-tube

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  dio: ^5.7.0
  one_of: ^1.5.0
  one_of_serializer: ^1.5.0
  built_value: ^8.9.3
  built_collection: ^5.1.1
  dio_http_formatter: ^3.3.0

dev_dependencies:
  built_value_generator: ^8.9.3
  build_runner: ^2.4.14
  test: ^1.25.14
  lints: ^5.1.1


